import { SignInButton, useUser } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";
import { api } from "~/utils/api";
import type { RouterOutputs } from "~/utils/api";

import dayjs from "dayjs";
import relativeTime from "dayjs/plugin/relativeTime";
import Image from "next/image";

dayjs.extend(relativeTime);

const CreatePostWizard = () => {
  const { user } = useUser();

  if (!user) {
    return null;
  }

  return (
    <div className="flex gap-3">
      <Image
        width={48}
        height={48}
        src={user.profileImageUrl}
        alt="Profile image"
        className="h-12 w-12 rounded-full"
      />
      <input
        placeholder="Type some emojis!"
        className="grow bg-transparent p-2 outline-none"
      />
    </div>
  );
};

type PostWithUser = RouterOutputs["posts"]["getAll"][number];
const PostView = (props: PostWithUser) => {
  const { post, author } = props;

  return (
    <div
      key={post.id}
      className="flex items-center gap-3 border-b border-slate-400 p-4"
    >
      <Image
        width={32}
        height={32}
        src={author.profileImageUrl}
        alt="profile user picture"
        className="mr-2 h-8 w-8 rounded-full"
      />

      <div>
        <div className="flex text-slate-400">
          <span className="mr-2">{`@${author.username}`}</span>
          <span>{dayjs(post.createdAt).fromNow()}</span>
        </div>
        <span>{post.content}</span>
      </div>
    </div>
  );
};

const Home: NextPage = () => {
  const { isSignedIn } = useUser();
  const { data: posts } = api.posts.getAll.useQuery();

  if (!posts) {
    return <div>Loading...</div>;
  }

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen justify-center">
        <div className="w-full border-x border-slate-400 md:max-w-2xl">
          <div className="border-b border-slate-400 p-4">
            {isSignedIn ? (
              <CreatePostWizard />
            ) : (
              <div className="bg-blue-700 p-2 text-center">
                <SignInButton />
              </div>
            )}
          </div>
          <div className="flex flex-col">
            {posts?.map((postWithUser) => (
              <PostView {...postWithUser} key={postWithUser.post.id} />
            ))}
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
