import { SignInButton, useUser } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";
import { api } from "~/utils/api";
import type { RouterOutputs } from "~/utils/api";

import dayjs from "dayjs";
import relativeTime from "dayjs/plugin/relativeTime";
import Image from "next/image";
import { LoadingPage } from "~/components/Loading";
import { useState } from "react";

dayjs.extend(relativeTime);

const CreatePostWizard = () => {
  const { user } = useUser();
  const [input, setInput] = useState("");
  const ctx = api.useContext();

  const { mutate, isLoading } = api.posts.create.useMutation({
    onSuccess: () => {
      setInput("");
      void ctx.posts.getAll.invalidate();
    },
  });

  if (!user) {
    return null;
  }

  return (
    <div className="flex gap-3">
      <Image
        width={48}
        height={48}
        src={user.profileImageUrl}
        alt="Profile image"
        className="h-12 w-12 rounded-full"
      />
      <input
        placeholder="Type some emojis!"
        className="grow bg-transparent p-2 outline-none"
        value={input}
        onChange={(e) => setInput(e.target.value)}
      />
      <button disabled={isLoading} onClick={() => mutate({ content: input })}>
        Submit
      </button>
    </div>
  );
};

type PostWithUser = RouterOutputs["posts"]["getAll"][number];
const PostView = (props: PostWithUser) => {
  const { post, author } = props;

  return (
    <div
      key={post.id}
      className="flex items-center gap-3 border-b border-slate-400 p-4"
    >
      <Image
        width={32}
        height={32}
        src={author.profileImageUrl}
        alt="profile user picture"
        className="mr-2 h-8 w-8 rounded-full"
      />

      <div>
        <div className="flex text-slate-400">
          <span className="mr-2">{`@${author.username}`}</span>
          <span>{dayjs(post.createdAt).fromNow()}</span>
        </div>
        <span className="text-xl">{post.content}</span>
      </div>
    </div>
  );
};

const Feed = () => {
  const { data: posts, isFetched: postsLoaded } = api.posts.getAll.useQuery();

  if (!postsLoaded) {
    return <LoadingPage />;
  }

  return (
    <div className="flex flex-col">
      {posts?.map((postWithUser) => (
        <PostView {...postWithUser} key={postWithUser.post.id} />
      ))}
    </div>
  );
};

const Home: NextPage = () => {
  const { isSignedIn, isLoaded: userLoaded } = useUser();
  // Start fetching asap
  const { isFetched: postsLoaded } = api.posts.getAll.useQuery();

  // Return empty div if both user and posts are not loaded since user tends to load faster
  if (!userLoaded && !postsLoaded) {
    return <div />;
  }

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen justify-center">
        <div className="w-full border-x border-slate-400 md:max-w-2xl">
          <div className="border-b border-slate-400 p-4">
            {isSignedIn ? (
              <CreatePostWizard />
            ) : (
              <div className="bg-blue-700 p-2 text-center">
                <SignInButton />
              </div>
            )}
          </div>
          <Feed />
        </div>
      </main>
    </>
  );
};

export default Home;
