import { SignIn, SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";
import { api } from "~/utils/api";

const Home: NextPage = () => {
  const { isSignedIn, user } = useUser();
  const { data: posts } = api.posts.getAll.useQuery();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        {isSignedIn ? (
          <>
            <h1 className="text-4xl text-white">Welcome {user.firstName}!</h1>
            <SignOutButton />
          </>
        ) : (
          <SignInButton />
        )}
        <SignIn path="/sign-in" routing="path" signUpUrl="/sign-up" />
        <div>
          {posts?.map((post) => (
            <div key={post.id}>
              <h1>{post.content}</h1>
            </div>
          ))}
        </div>
      </main>
    </>
  );
};

export default Home;
